import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { ModuleRegistry } from "ag-grid-community";
import {
  ClientSideRowModelModule,
  EnterpriseCoreModule,
  ColumnsToolPanelModule,
  FiltersToolPanelModule,
  SideBarModule,
} from "ag-grid-enterprise";

ModuleRegistry.registerModules([
  EnterpriseCoreModule,
  ClientSideRowModelModule,
  ColumnsToolPanelModule,
  FiltersToolPanelModule,
  SideBarModule,
]);

import "./globals.css";
import AgGridWrapper from "@/components/ag-grid-wrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NuqsAdapter>
          <AgGridWrapper>
            <div className="p-5">{children}</div>
          </AgGridWrapper>
        </NuqsAdapter>
      </body>
    </html>
  );
}
